CC = javac
RR = java
bins = run


all: $(bins)

gen: Main.java
	$(CC) Main.java

run:
	$(RR) --enable-preview -XX:+ShowCodeDetailsInExceptionMessages -Dfile.encoding=UTF-8 -cp 'C:\Users\ACER\AppData\Roaming\Code\User\workspaceStorage\0a349c391de58fd5b309547879e5fc12\redhat.java\jdt_ws\java-breakout_c4cefadd\bin' brickbreak.Main

clean: 
	rm  *.class